[package]
name = "sequoia-sq"
description = "Command-line frontends for Sequoia"
version = "0.31.0"
authors = [
    "Azul <azul@sequoia-pgp.org>",
    "Heiko Schaefer <heiko@schaefer.name>",
    "Igor Matuszewski <igor@sequoia-pgp.org>",
    "Justus Winter <justus@sequoia-pgp.org>",
    "Kai Michaelis <kai@sequoia-pgp.org>",
    "Lars Wirzenius <liw@sequoia-pgp.org>",
    "Neal H. Walfield <neal@sequoia-pgp.org>",
    "Nora Widdecke <nora@sequoia-pgp.org>",
    "Wiktor Kwapisiewicz <wiktor@sequoia-pgp.org>",
]
build = "build.rs"
documentation = "https://docs.rs/sequoia-sq"
homepage = "https://sequoia-pgp.org/"
repository = "https://gitlab.com/sequoia-pgp/sequoia-sq"
readme = "README.md"
keywords = ["cryptography", "openpgp", "pgp", "encryption", "signing"]
categories = ["cryptography", "authentication", "command-line-utilities"]
license = "GPL-2.0-or-later"
edition = "2021"
rust-version = "1.63"

[badges]
gitlab = { repository = "sequoia-pgp/sequoia-sq" }
maintenance = { status = "actively-developed" }

[dependencies]
buffered-reader = { version = "1.0.0", default-features = false, features = ["compression-deflate"] }
dirs = "5"
dot-writer = "0.1.3"
sequoia-openpgp = { version = "1.13", default-features = false, features = ["compression-deflate"] }
sequoia-autocrypt = { version = "0.25", default-features = false, optional = true }
sequoia-net = { version = "0.27", default-features = false }
sequoia-policy-config = "0.6"
anyhow = "1.0.18"
chrono = "0.4.10"
# For an MSRV of 1.63: 4.0.32.
clap = { version = "4", features = ["derive", "env", "string", "wrap_help"] }
itertools = ">=0.10, <0.11"
once_cell = "1.17"
sequoia-cert-store = "0.3"
sequoia-wot = "0.8"
tempfile = "3.1"
tokio = { version = "1.13.1" }
rpassword = "7.0"
serde_json = "1.0.80"
serde = { version = "1.0.137", features = ["derive"] }
roff = "0.2.1"
terminal_size = "0.2.6"
is-terminal = "0.4.7"
termcolor = "1.2.0"

[build-dependencies]
anyhow = "1.0.18"
buffered-reader = { version = "1.0.0", default-features = false, features = ["compression-deflate"] }
# For an MSRV of 1.63: 4.0.32
clap = { version = "4", features = ["derive", "env", "string", "wrap_help"] }
# For an MSRV of 1.63: 4.0.7.
clap_complete = "4"
# For an MSRV of 1.63: 0.2.6
clap_mangen = "0.2"
chrono = "0.4.10"
sequoia-openpgp = { version = "1.13", default-features = false }
sequoia-net = { version = "0.27", default-features = false }
subplot-build = { version = "0.7.0", optional = true }
cfg-if = "1"
terminal_size = "0.2.6"

[dev-dependencies]
subplotlib = "0.7.0"
fehler = "1.0.0"
# For an MSRV of 1.63: 2.0.8.
assert_cmd = "2"
# For an MSRV of 1.63: 2.1.5
predicates = "2"

[[bin]]
name = "sq"
path = "src/sq.rs"
bench = false

[features]
default = [
    "crypto-nettle",
    "compression-bzip2",
    "autocrypt",
]
crypto-nettle = ["sequoia-openpgp/crypto-nettle"]
crypto-openssl = ["sequoia-openpgp/crypto-openssl"]
crypto-botan = ["sequoia-openpgp/crypto-botan"]
crypto-botan2 = ["sequoia-openpgp/crypto-botan2"]
crypto-cng = ["sequoia-openpgp/crypto-cng"]
crypto-rust = ["sequoia-openpgp/crypto-rust"]
compression-bzip2 = ["sequoia-openpgp/compression-bzip2"]
autocrypt = ["sequoia-autocrypt"]
subplot = ["subplot-build"]

[profile.release]
debug = true
