[advisories]
ignore = [
  "RUSTSEC-2020-0159",
  "RUSTSEC-2020-0071", # chrono not affected by time 0.1 issue
  # fehler is unmaintained.
  #
  # fehler is used by subplot and thus an indirect dependency.  Remove
  # when a new version subplot is released without fehler.  See
  # https://gitlab.com/subplot/subplot/-/issues/340.
  "RUSTSEC-2023-0067",

  # yaml-rust is unmaintained.
  #
  # yaml-rust is used by subplot/roadmap/serde_yaml thus an indirect
  # dependency.  Remove when a new version of roadmap is released that
  # uses a newer version of serde_yaml.  See
  # https://gitlab.com/larswirzenius/roadmap/-/issues/13
  "RUSTSEC-2024-0320",
]
unmaintained = "deny"
yanked = "deny"

[bans]
multiple-versions = "allow"
deny = [
  # does not have responsible disclosure policy:
  # https://github.com/briansmith/ring#bug-reporting
  {name = "ring"},
]

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "GPL-2.0",
  "GPL-3.0",
  "ISC",
  "LGPL-2.0",
  "LGPL-3.0",
  "MIT",
  "MIT-0",
  "MPL-2.0",
  "Unicode-DFS-2016",
  "Unicode-3.0",
]
