[advisories]
ignore = [
  "RUSTSEC-2020-0071", # chrono not affected by time 0.1 issue
  # fehler is unmaintained.
  #
  # fehler is used by subplot and thus an indirect dependency.  Remove
  # when a new version subplot is released without fehler.  See
  # https://gitlab.com/subplot/subplot/-/issues/340.
  "RUSTSEC-2023-0067",
]
unmaintained = "deny"
yanked = "deny"

[bans]
multiple-versions = "allow"
deny = [
  # does not have responsible disclosure policy:
  # https://github.com/briansmith/ring#bug-reporting
  {name = "ring"},
]

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "GPL-2.0",
  "GPL-3.0",
  "ISC",
  "LGPL-2.0",
  "LGPL-3.0",
  "MIT",
  "MIT-0",
  "MPL-2.0",
  "Unicode-DFS-2016",
]
